version: "3.9"

services:
  app_pettiway:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      pettiway:
        condition: service_healthy
    networks:
      - mynetwork

  pettiway:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      retries: 10
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
